title_book = input("Title of the book: ")
author = input("Author: ")
number= input("Number of pages: ")
print(title_book.replace(" ", "").isalpha())
print(author.replace(" ", "").isalpha())
print(number.isdigit())
print(f"{title_book.capitalize()}: {author.title()}, {number}")
book= title_book+author+str(number)
print(len(book))
